package de.thro.inf.prg3.a07;

import de.thro.inf.prg3.a07.api.OpenMensaAPI;
import de.thro.inf.prg3.a07.controllers.MainController;
import de.thro.inf.prg3.a07.model.Meal;
import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import retrofit2.Call;
import retrofit2.Retrofit;
import retrofit2.converter.gson.GsonConverterFactory;

import java.io.IOException;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App extends Application{

	public static void main(String[] args)  throws IOException
	{/*
		Retrofit retrofit = new Retrofit.Builder()
			.baseUrl("https://openmensa.org")
			.addConverterFactory(GsonConverterFactory.create())
			.build();

		OpenMensaAPI Inteface = retrofit.create(OpenMensaAPI.class);
		Call<List<Meal>> call = Inteface.getMeals("2015-06-10");
		MainController mainController = new MainController();
		mainController.observableMealList = FXCollections.observableList(call.execute().body());
		for(Meal m: mainController.observableMealList)
		{
			//System.out.println(m.toString() + "\n");
		}
		//System.out.println(mainController.observableMealList.get(0).isVegetarian());*/
		launch(args);

		System.exit(0);
	}

	@Override
	public void start(Stage stage) throws Exception {
		Parent root = FXMLLoader.load(getClass().getResource("views/main.fxml"));
		stage.setTitle("Cafeteria");
		stage.setScene(new Scene(root, 800, 600));
		stage.show();

	}
}
