#ifndef INC_03_INHERITANCE_AND_POLYMORPHISM_BICYCLE_H
#define INC_03_INHERITANCE_AND_POLYMORPHISM_BICYCLE_H


// TODO: Define your Bicycle class


#endif //INC_03_INHERITANCE_AND_POLYMORPHISM_BICYCLE_H
