#ifndef INC_03_INHERITANCE_AND_POLYMORPHISM_MOTORCYCLE_H
#define INC_03_INHERITANCE_AND_POLYMORPHISM_MOTORCYCLE_H


// TODO: Define your Motorcycle class


#endif //INC_03_INHERITANCE_AND_POLYMORPHISM_MOTORCYCLE_H
