#ifndef INC_03_INHERITANCE_AND_POLYMORPHISM_TRICYCLE_H
#define INC_03_INHERITANCE_AND_POLYMORPHISM_TRICYCLE_H


// TODO: Define your Tricycle class


#endif //INC_03_INHERITANCE_AND_POLYMORPHISM_TRICYCLE_H
