#ifndef INC_03_INHERITANCE_AND_POLYMORPHISM_AMPHIBIOUSCAR_H
#define INC_03_INHERITANCE_AND_POLYMORPHISM_AMPHIBIOUSCAR_H


// TODO: Define the AmphibiousCar class


#endif //INC_03_INHERITANCE_AND_POLYMORPHISM_AMPHIBIOUSCAR_H
