#ifndef INC_03_INHERITANCE_AND_POLYMORPHISM_VEHICLE_H
#define INC_03_INHERITANCE_AND_POLYMORPHISM_VEHICLE_H


// TODO: Define the Vehicle class


#endif //INC_03_INHERITANCE_AND_POLYMORPHISM_VEHICLE_H
